name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.0.1
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  build: ^3.0.2
  source_gen: ^3.1.0
  hive: ^2.2.3
  analyzer: ^8.1.1
  source_helper: ^1.1.0

dev_dependencies:
  test: ^1.22.0
  build_test: ^3.3.2       # upgraded to be compatible with build 3.x
  build_runner: ^2.7.0
  lints: ^6.0.0
