name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.0.1
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  build: ^2.1.0
  source_gen: ^1.5.0
  hive: ^2.2.3
  analyzer: ^6.0.0
  source_helper: ^1.1.0

dev_dependencies:
  test: ^1.22.0
  build_test: ^2.1.0
  build_runner: ^2.4.13
  lints: ^6.0.0
